/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIdRouteImport } from './routes/workspace.$id'
import { Route as PreviewIdRouteImport } from './routes/preview.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdRoute = WorkspaceIdRouteImport.update({
  id: '/workspace/$id',
  path: '/workspace/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewIdRoute = PreviewIdRouteImport.update({
  id: '/preview/$id',
  path: '/preview/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboard': typeof OnboardRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/preview/$id': typeof PreviewIdRoute
  '/workspace/$id': typeof WorkspaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboard': typeof OnboardRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/preview/$id': typeof PreviewIdRoute
  '/workspace/$id': typeof WorkspaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboard': typeof OnboardRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/preview/$id': typeof PreviewIdRoute
  '/workspace/$id': typeof WorkspaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/dashboard'
    | '/login'
    | '/notifications'
    | '/onboard'
    | '/profile'
    | '/sitemap.xml'
    | '/preview/$id'
    | '/workspace/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/dashboard'
    | '/login'
    | '/notifications'
    | '/onboard'
    | '/profile'
    | '/sitemap.xml'
    | '/preview/$id'
    | '/workspace/$id'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/dashboard'
    | '/login'
    | '/notifications'
    | '/onboard'
    | '/profile'
    | '/sitemap.xml'
    | '/preview/$id'
    | '/workspace/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardRoute: typeof OnboardRoute
  ProfileRoute: typeof ProfileRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PreviewIdRoute: typeof PreviewIdRoute
  WorkspaceIdRoute: typeof WorkspaceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$id': {
      id: '/workspace/$id'
      path: '/workspace/$id'
      fullPath: '/workspace/$id'
      preLoaderRoute: typeof WorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$id': {
      id: '/preview/$id'
      path: '/preview/$id'
      fullPath: '/preview/$id'
      preLoaderRoute: typeof PreviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardRoute: OnboardRoute,
  ProfileRoute: ProfileRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PreviewIdRoute: PreviewIdRoute,
  WorkspaceIdRoute: WorkspaceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
